### PR TITLE
took out special power parameters, fixes for telephony webapi, and some neats

### PR DESCRIPTION
**Pull request by ypwalter**
Telephony should be fine and runs smooth now.

@ShakoHo r?

### CODE REVIEW

**Comment by ShakoHo** [comment]
when I tried to run telephony sub suite in my local environment, it will failed to disable dialer agent...r-

**Comment by ypwalter** [comment]
@ShakoHo  r?

**Comment by ypwalter** [comment]
@ShakoHo r?

**Comment by ypwalter** [comment]
@ShakoHo r?

**Comment by ShakoHo** [comment]
test and verified with aries build 20150902203922 r+

**Pull request merged**
