### PR TITLE
bug 1142409 - add v2.2 to support version list

### PR DESCRIPTION
**Pull request by altsai**
add v2.2 to support list

### CODE REVIEW

**Comment by askeing** [comment]
```
 0:00.82 LOG: MainThread CRITICAL Error during precondition check:
Traceback (most recent call last):
  File "/home/askeing/workspace/fxos-certsuite/certsuite/harness.py", line 245, in check_preconditions
    passed = precondition(device)
  File "/home/askeing/workspace/fxos-certsuite/certsuite/harness.py", line 233, in <lambda>
    check_marionette_installed = lambda device: install_marionette(device, config['version'])
  File "/home/askeing/workspace/fxos-certsuite/certsuite/harness.py", line 287, in install_marionette
    marionette_install(version)
  File "/home/askeing/workspace/fxos-certsuite/.env/local/lib/python2.7/site-packages/marionette_extension-0.4.7-py2.7.egg/marionette_extension/installer.py", line 44, in install
    raise Exception("%s not in supported versions: %s" % (version, SUPPORTED_VERSIONS))
Exception: 2.2 not in supported versions: ['1.3', '1.4', '2.0', '2.1']
```
It seems like we still have to update the code of `marionette_extension`, then update the requirements [1].

[1] https://github.com/mozilla-b2g/fxos-certsuite/blob/master/requirements.txt#L4

**Comment by askeing** [comment]
Source code of `marionette_extension`:
https://github.com/mozilla-b2g/marionette-extension/blob/master/marionette_extension/installer.py

**Comment by altsai** [comment]
I filed two bugs to follow up the upgrade of marionette_extension and fxosapp-gen libraries.

**Comment by altsai** [comment]
All webapi testing will be blocked by above two libraries.

**Pull request merged**
