### PR TITLE
bug 1139760: Enhance Report to generate PDF version

### PR DESCRIPTION
**Pull request by oouyang**
report enhance: 1. add details for no failed 2. use html.pre for python traceback to let html view the information readable

### CODE REVIEW

**Comment by askeing** [comment]
LGTM

**Comment by oouyang** [comment]
update PDF report generation

Note: need to install texlive texlive-extra pandoc

sudo apt-get install texlive texlive-latex-extra pandoc

**Comment by askeing** [comment]
How about adding the `README.md` file under `certsuite/static/report/` folder?
So we can tell user that the pdf generation needs the following packages, `texlive texlive-extra pandoc`.

**Comment by oouyang** [comment]
I add prerun.sh and it called in run.sh to install required packages

**Comment by altsai** [comment]
LGTM

**Pull request closed without merging**
